### ISSUE TITLE
fireBaseAppName configuration documentation is wrong.

### ISSUE THREAD

**Issue by jemware** [ibroadfo/ember-cli-deploy-firebase#1]
First off, thank you for putting this plugin together!

The following configuration from the README does not work:

```js
ENV["firebase"] = {
  fireBaseAppName: 'your-firebase-app-name'
}
```

If you log `options.firebase` in the addon’s `index.js` it returns `undefined`. This causes deployment to default to whatever is in firebase.json. My workaround was to configure my project like so: `ENV.fireBaseAppName = 'your-firebase-app-name';`

I would do a pr, but I’m not sure if you want to change the docs, or how the configuration is being read.

**Comment by ibroadfo** [comment]
Thanks for spotting this! I think i copy and pasted a little too eagerly from other plugins when putting the docs together. :)

**Comment by ibroadfo** [comment]
I also wanted to say: thank you for making my first public issue such a positive experience. :)

**Comment by jemware** [comment]
Aw geez, no problem! Golden rule and what not :-D Personally I’m terrified to put anything on github!

Thanks again for making the plugin. It facilitated me dumping my cobbled together deploy script for a full ember-cli-deploy pipeline.

**Comment by ibroadfo** [comment]
It took me years to actually publish anything; I'd advise just going for it. :)

I'm really pleased this is useful!
