### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by xypaul** [ibroadfo/ember-cli-deploy-firebase#2]
Hey thanks for creating this library :)

`ember deploy production`

isn't working for me. what's the sytax to run this library.

right now I am just using a `ember build` followed by a `firebase deploy` which works fine

Thanks :)

**Comment by ibroadfo** [comment]
Hi! :)

So you have to `ember install ember-cli-deploy` to get access to the deploy command; sorry for the lack of information, I'll update the docs shortly to reflect this.

Thanks for looking at the project and taking the time to report this problem!

**Comment by xypaul** [comment]
@ibroadfo cheers :)
